services:
# ==========================================
# 1. שירות אימות (Auth Service)
# ==========================================
  - type: web
    name: auth-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./auth_service
    buildCommand: npm install && npm install --save-dev @types/node @types/express typescript && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

# ==========================================
# 2. שירות אודיו (Speech to Text Service)
# ==========================================
  - type: web
    name: speach-to-text-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./speach-to-text-service          
    buildCommand: npm install && npm run build       
    startCommand: npm start
    autoDeploy: true                                  
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SERVICE_URL
        fromService:
          type: web
          name: auth-service
          property: host