services:
# ==========================================
# 1. שירות אימות (Auth Service)
# ==========================================
  - type: web
    name: auth-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./auth-service
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: sola-project         

# ==========================================
# 2. שירות אודיו (Speech to Text Service)
# ==========================================
  - type: web
    name: speach-to-text-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./speach-to-text-service          
    buildCommand: npm install && npm run build       
    startCommand: npm start
    autoDeploy: true                                  
    envVars:
      - key: NODE_ENV
        value: production      
      - fromGroup: sola-project             
      
# ==========================================
# 3. Report-Service
# ==========================================
  - type: web
    name: report-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./report-service          
    buildCommand: npm install && npm run build       
    startCommand: npm start
    autoDeploy: true                                  
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SERVICE_URL
        sync: false
      - fromGroup: sola-project         

# ==========================================
# 4. Calendar-Service
# ==========================================
  - type: web
    name: calendar-service
    env: node
    plan: free
    repo: https://github.com/diversi-tech/sola
    branch: main
    rootDir: ./calendar-service          
    buildCommand: npm install && npm run build       
    startCommand: npm run dev
    autoDeploy: true                                  
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: sola-project         